workflows:
  custom-ios-build:
    name: Custom iOS Build
    max_build_duration: 120
    environment:
      xcode: 16.1
      flutter: 3.22.0
      vars:
        IPHONEOS_DEPLOYMENT_TARGET: "12.0"
    scripts:
      - name: Build iOS
        script: |
          #!/bin/sh
          set -e
          echo "Starting pre-build script..."
          flutter clean
          flutter pub get
          cd ios
          echo "Running pod deintegrate..."
          pod deintegrate
          echo "Cleaning pod cache..."
          pod cache clean --all
          rm -rf Pods
          rm -f Podfile.lock
          echo "Running pod install..."
          pod install --repo-update
          echo "Checking for Runner.xcworkspace..."
          ls -la
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "Error: Runner.xcworkspace not found after pod install!"
            exit 1
          fi
          echo "Forcing iOS 12.0 in project.pbxproj..."
          find . -name "project.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' {} \;
          echo "Copying provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /Users/builder/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/ || true
          echo "Listing provisioning profiles..."
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "Running xcodebuild archive..."
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug -archivePath build/Runner.xcarchive archive -sdk iphoneos IPHONEOS_DEPLOYMENT_TARGET=12.0 DEVELOPMENT_TEAM=X89LJ3ZB4R
          echo "Running xcodebuild export..."
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ../export_options.plist -exportPath build/ipa
          echo "Moving .ipa..."
          mv build/ipa/Runner.ipa ../Runner.ipa
          echo "Build completed successfully!"
    artifacts:
      - Runner.ipa