// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcbwlLv2hzIH4SXgz20GcozWJH5lsZBI',
    appId: '1:828161650526:web:3b02f4dca86ebdc927e9cf',
    messagingSenderId: '828161650526',
    projectId: 'bettingapp-d6a38',
    authDomain: 'bettingapp-d6a38.firebaseapp.com',
    storageBucket: 'bettingapp-d6a38.firebasestorage.app',
    measurementId: 'G-10HEBBCFG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHT8_XCzNLA6YbvN7u6J6fCY6BvyB7-2k',
    appId: '1:828161650526:android:d84f9b90798417b727e9cf',
    messagingSenderId: '828161650526',
    projectId: 'bettingapp-d6a38',
    storageBucket: 'bettingapp-d6a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKURn0Rs4_MnIXywjRm-LB8BuzSc_YZBg',
    appId: '1:828161650526:ios:a43c14e6ffb0e48127e9cf',
    messagingSenderId: '828161650526',
    projectId: 'bettingapp-d6a38',
    storageBucket: 'bettingapp-d6a38.firebasestorage.app',
    iosBundleId: 'com.example.betdofeApp',
  );
}
